# Generated by Django 4.2.18 on 2025-03-13 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        choices=[
                            ("Monday 8:00 AM - 10:00 AM", "Monday 8:00 AM - 10:00 AM"),
                            (
                                "Monday 10:00 AM - 12:00 PM",
                                "Monday 10:00 AM - 12:00 PM",
                            ),
                            ("Monday 12:00 PM - 2:00 PM", "Monday 12:00 PM - 2:00 PM"),
                            ("Monday 2:00 PM - 4:00 PM", "Monday 2:00 PM - 4:00 PM"),
                            ("Monday 4:00 PM - 6:00 PM", "Monday 4:00 PM - 6:00 PM"),
                            (
                                "Tuesday 8:00 AM - 10:00 AM",
                                "Tuesday 8:00 AM - 10:00 AM",
                            ),
                            (
                                "Tuesday 10:00 AM - 12:00 PM",
                                "Tuesday 10:00 AM - 12:00 PM",
                            ),
                            (
                                "Tuesday 12:00 PM - 2:00 PM",
                                "Tuesday 12:00 PM - 2:00 PM",
                            ),
                            ("Tuesday 2:00 PM - 4:00 PM", "Tuesday 2:00 PM - 4:00 PM"),
                            ("Tuesday 4:00 PM - 6:00 PM", "Tuesday 4:00 PM - 6:00 PM"),
                            (
                                "Wednesday 8:00 AM - 10:00 AM",
                                "Wednesday 8:00 AM - 10:00 AM",
                            ),
                            (
                                "Wednesday 10:00 AM - 12:00 PM",
                                "Wednesday 10:00 AM - 12:00 PM",
                            ),
                            (
                                "Wednesday 12:00 PM - 2:00 PM",
                                "Wednesday 12:00 PM - 2:00 PM",
                            ),
                            (
                                "Wednesday 2:00 PM - 4:00 PM",
                                "Wednesday 2:00 PM - 4:00 PM",
                            ),
                            (
                                "Wednesday 4:00 PM - 6:00 PM",
                                "Wednesday 4:00 PM - 6:00 PM",
                            ),
                            (
                                "Thursday 8:00 AM - 10:00 AM",
                                "Thursday 8:00 AM - 10:00 AM",
                            ),
                            (
                                "Thursday 10:00 AM - 12:00 PM",
                                "Thursday 10:00 AM - 12:00 PM",
                            ),
                            (
                                "Thursday 12:00 PM - 2:00 PM",
                                "Thursday 12:00 PM - 2:00 PM",
                            ),
                            (
                                "Thursday 2:00 PM - 4:00 PM",
                                "Thursday 2:00 PM - 4:00 PM",
                            ),
                            (
                                "Thursday 4:00 PM - 6:00 PM",
                                "Thursday 4:00 PM - 6:00 PM",
                            ),
                            ("Friday 8:00 AM - 10:00 AM", "Friday 8:00 AM - 10:00 AM"),
                            (
                                "Friday 10:00 AM - 12:00 PM",
                                "Friday 10:00 AM - 12:00 PM",
                            ),
                            ("Friday 12:00 PM - 2:00 PM", "Friday 12:00 PM - 2:00 PM"),
                            ("Friday 2:00 PM - 4:00 PM", "Friday 2:00 PM - 4:00 PM"),
                            ("Friday 4:00 PM - 6:00 PM", "Friday 4:00 PM - 6:00 PM"),
                        ],
                        default="Monday 8:00 AM - 10:00 AM",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("teacher", models.CharField(max_length=100)),
                ("credits", models.PositiveIntegerField(default=0)),
                ("capacity", models.PositiveIntegerField(default=30)),
                ("enrolled_students", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Notification", max_length=100)),
                ("message", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_global", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
